# Generated by Django 5.1.1 on 2024-09-12 22:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('species', models.CharField(max_length=100)),
                ('type_animal', models.CharField(max_length=5)),
                ('status_code', models.CharField(max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('cellphone', models.CharField(max_length=9)),
                ('status_code', models.CharField(max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.TextField(null=True)),
            ],
        ),
    ]
